# RadMarky uses major.minor.build versioning with an optional prerelease suffix.
# Increment RADMARKY_VERSION_BUILD for every release build.
set(RADMARKY_VERSION_MAJOR 1)
set(RADMARKY_VERSION_MINOR 0)
set(RADMARKY_VERSION_BUILD 0)
set(RADMARKY_VERSION_SUFFIX "-rc.3")
set(RADMARKY_RELEASE_DATE "September 2, 2026")

set(RADMARKY_VERSION_BASE
    "${RADMARKY_VERSION_MAJOR}.${RADMARKY_VERSION_MINOR}.${RADMARKY_VERSION_BUILD}")
set(RADMARKY_VERSION "${RADMARKY_VERSION_BASE}${RADMARKY_VERSION_SUFFIX}")
